homeassistant:
  name: Home
  unit_system: imperial
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  time_zone: !secret home_timezone
  customize: !include_dir_merge_named customize

updater:
discovery:
frontend:
history:
logbook:
sun:

http:
  api_password: !secret http_password
ifttt:
  key: !secret ifttt_key
tts:
  platform: google
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
light:
  platform: hue

automation: !include_dir_merge_list automation
group: !include_dir_merge_named group
media_player: !include_dir_merge_list media_player
scene: !include_dir_merge_list scene
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
