homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone

updater:
discovery:
frontend:
history:
logbook:
sun:

http:
  api_password: !secret http_password
ifttt:
  key: !secret ifttt_key
tts:
  platform: google

automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
