homeassistant:
  name: Home
  latitude: !secrets home_lat
  longitude: !secrets home_long
  elevation: !secrets home_elevation
  unit_system: imperial
  time_zone: !secrets home_timezone

updater:
discovery:
frontend:
history:
logbook:
sun:

http:
  api_password: !secrets http_password
ifttt:
  key: !secrets ifttt_key
tts:
  platform: google

automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
sensor: !include_dir_merge_list sensor
switch: !include_dir_merge_list switch
