- platform: command_line
  switches:
    playstation4:
      command_on: 'ps4-waker'
      command_off: 'ps4-waker standby'
      command_state: 'ps4-waker search | grep -qi "200 Ok"'
      friendly_name: "Playstation 4"

