- platform: darksky
  api_key: c10d916a31d2d949edacf7eff5f33c78
  monitored_conditions:
    - temperature
    - humidity
    - wind_speed
    - precip_intensity
    - precip_probability
    - temperature_max
    - temperature_min
    - cloud_cover
