- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      from: 'playing'
      to: 'paused'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_normal

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
      from: 'paused'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
      service: scene.turn_on
      entity_id: scene.livingroom_dim

