- alias: "TV Off"
  trigger:
    - platform: state
      entity_id: media_player.hisense_roku_tv
      from: 'playing'
      to: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.tv_on
- alias: "TV On"
  trigger:
    - platform: state
      entity_id: media_player.hisense_roku_tv
      from: 'home'
      to: 'playing'
  action:
    service: scene.turn_on
    entity_id: scene.tv_off

